import type { Curriculum, ExerciseType, LessonExercise, Phrase, Scenario } from '../types'

export const survivalPhrases: Phrase[] = [
  {
    id: 'namaskara-saar',
    kannada: 'ನಮಸ್ಕಾರ ಸಾರ್',
    transliteration: 'namaskara saar',
    english: 'Hello sir',
    context: 'A polite greeting for shops, autos, and apartment security.',
    skillTag: 'greetings',
  },
  {
    id: 'dhanyavada',
    kannada: 'ಧನ್ಯವಾದ',
    transliteration: 'dhanyavada',
    english: 'Thank you',
    context: 'Use after getting help at a darshini or kirana store.',
    skillTag: 'greetings',
  },
  {
    id: 'hegiddira',
    kannada: 'ಹೇಗಿದ್ದೀರಾ?',
    transliteration: 'hegiddira?',
    english: 'How are you?',
    context: 'Respectful small talk with neighbors or office staff.',
    skillTag: 'greetings',
  },
  {
    id: 'chennagiddene',
    kannada: 'ಚೆನ್ನಾಗಿದ್ದೇನೆ',
    transliteration: 'chennagiddene',
    english: 'I am fine',
    context: 'A safe answer when someone asks how you are.',
    skillTag: 'greetings',
  },
  {
    id: 'hesaru-enu',
    kannada: 'ನಿಮ್ಮ ಹೆಸರು ಏನು?',
    transliteration: 'nimma hesaru enu?',
    english: 'What is your name?',
    context: 'Useful in introductions with tutors, guards, or classmates.',
    skillTag: 'introductions',
  },
  {
    id: 'nanna-hesaru',
    kannada: 'ನನ್ನ ಹೆಸರು ರಾಹುಲ್',
    transliteration: 'nanna hesaru Rahul',
    english: 'My name is Rahul',
    context: 'Simple introduction with Kannada plus your own name.',
    skillTag: 'introductions',
  },
  {
    id: 'kannada-gothilla',
    kannada: 'ನನಗೆ ಕನ್ನಡ ಗೊತ್ತಿಲ್ಲ',
    transliteration: 'nanage kannada gothilla',
    english: 'I do not know Kannada',
    context: 'A survival phrase when a conversation gets too fast.',
    skillTag: 'survival',
  },
  {
    id: 'swalpa-kannada',
    kannada: 'ಸ್ವಲ್ಪ ಕನ್ನಡ ಬರುತ್ತದೆ',
    transliteration: 'swalpa kannada baruttade',
    english: 'I know a little Kannada',
    context: 'Encourages people to continue slowly in Kannada.',
    skillTag: 'survival',
  },
  {
    id: 'nidhanavagi-heli',
    kannada: 'ನಿಧಾನವಾಗಿ ಹೇಳಿ',
    transliteration: 'nidhanavagi heli',
    english: 'Please speak slowly',
    context: 'Helpful with BMTC conductors and busy shopkeepers.',
    skillTag: 'listening',
  },
  {
    id: 'matte-heli',
    kannada: 'ಮತ್ತೆ ಹೇಳಿ',
    transliteration: 'matte heli',
    english: 'Please say it again',
    context: 'Use when you miss a word in traffic or market noise.',
    skillTag: 'listening',
  },
  {
    id: 'hogbeku',
    kannada: 'ಹೋಗಬೇಕು',
    transliteration: 'hogbeku',
    english: 'need to go',
    context: 'Core travel word for autos, buses, and directions.',
    skillTag: 'verbs',
  },
  {
    id: 'majestic-ge-hogbeku',
    kannada: 'ಮೆಜೆಸ್ಟಿಕ್‌ಗೆ ಹೋಗಬೇಕು',
    transliteration: 'Majestic-ge hogbeku',
    english: 'I need to go to Majestic',
    context: 'A common Bangalore auto or BMTC destination sentence.',
    skillTag: 'transport',
  },
  {
    id: 'eshtu',
    kannada: 'ಎಷ್ಟು?',
    transliteration: 'eshtu?',
    english: 'How much?',
    context: 'Ask prices for autos, vegetables, tickets, and tea.',
    skillTag: 'shopping',
  },
  {
    id: 'ticket-eshtu',
    kannada: 'ಟಿಕೆಟ್ ಎಷ್ಟು?',
    transliteration: 'ticket eshtu?',
    english: 'How much is the ticket?',
    context: 'BMTC bus phrase when the conductor asks your destination.',
    skillTag: 'transport',
  },
  {
    id: 'illi-nillisi',
    kannada: 'ಇಲ್ಲಿ ನಿಲ್ಲಿಸಿ',
    transliteration: 'illi nillisi',
    english: 'Stop here',
    context: 'Use in an auto or cab when you reach the gate.',
    skillTag: 'transport',
  },
  {
    id: 'barutte',
    kannada: 'ಬರುತ್ತೆ',
    transliteration: 'barutte',
    english: 'It will come',
    context: 'Common response while waiting for buses, food, or people.',
    skillTag: 'verbs',
  },
  {
    id: 'oota-aayta',
    kannada: 'ಊಟ ಆಯ್ತಾ?',
    transliteration: 'oota aayta?',
    english: 'Did you eat?',
    context: 'Friendly Bangalore small talk at work or PG.',
    skillTag: 'culture',
  },
  {
    id: 'swalpa-adjust-maadi',
    kannada: 'ಸ್ವಲ್ಪ ಅಡ್ಜಸ್ಟ್ ಮಾಡಿ',
    transliteration: 'swalpa adjust maadi',
    english: 'Please adjust a little',
    context: 'Classic Bangalore code-switching phrase in crowds and traffic.',
    skillTag: 'bangalore',
  },
  {
    id: 'beku',
    kannada: 'ಬೇಕು',
    transliteration: 'beku',
    english: 'want or need',
    context: 'Essential when ordering coffee, dosa, tickets, or help.',
    skillTag: 'shopping',
  },
  {
    id: 'beda',
    kannada: 'ಬೇಡ',
    transliteration: 'beda',
    english: 'do not want',
    context: 'Use to decline bags, extra chutney, or a route.',
    skillTag: 'shopping',
  },
]

export const lessonExercises: LessonExercise[] = [
  {
    id: 'survival-translate-1',
    type: 'translate',
    prompt: 'Translate this phrase:',
    kannada: 'ನಮಸ್ಕಾರ ಸಾರ್',
    transliteration: 'namaskara saar',
    answer: 'Hello sir',
    options: ['Hello sir', 'Goodbye sir', 'Thank you sir', 'How are you sir'],
    explanation: 'ನಮಸ್ಕಾರ ಸಾರ್ is a respectful hello used across Bangalore.',
    skillTag: 'greetings',
    xp: 2,
    vocabularyIds: ['namaskara-saar'],
  },
  {
    id: 'survival-arrange-1',
    type: 'arrange',
    prompt: 'Arrange the words:',
    english: 'Hello sir, how are you?',
    kannada: 'ನಮಸ್ಕಾರ ಸಾರ್ ಹೇಗಿದ್ದೀರಾ',
    answer: 'ನಮಸ್ಕಾರ ಸಾರ್ ಹೇಗಿದ್ದೀರಾ',
    options: ['ಸಾರ್', 'ಹೇಗಿದ್ದೀರಾ', 'ನಮಸ್ಕಾರ', 'ಚೆನ್ನಾಗಿದ್ದೇನೆ'],
    explanation: 'Kannada greetings usually keep the respectful ಸಾರ್ after the greeting.',
    skillTag: 'greetings',
    xp: 3,
    vocabularyIds: ['namaskara-saar', 'hegiddira'],
  },
  {
    id: 'survival-fill-1',
    type: 'fillBlank',
    prompt: 'Fill in the blank:',
    english: 'I need to go to school',
    kannada: 'ನಾನು ಶಾಲೆಗೆ ___',
    answer: 'ಹೋಗಬೇಕು',
    options: ['ಹೋಗಬೇಕು', 'ಬರುತ್ತೇನೆ', 'ತಿನ್ನುತ್ತೇನೆ', 'ಮಾಡುತ್ತೇನೆ'],
    explanation: 'ಹೋಗಬೇಕು means need to go.',
    skillTag: 'verbs',
    xp: 2,
    vocabularyIds: ['hogbeku'],
  },
  {
    id: 'survival-listening-1',
    type: 'listening',
    prompt: 'What did you hear?',
    kannada: 'ಟಿಕೆಟ್ ಎಷ್ಟು?',
    answer: 'ಟಿಕೆಟ್ ಎಷ್ಟು?',
    options: ['ನಮಸ್ಕಾರ', 'ಧನ್ಯವಾದ', 'ಟಿಕೆಟ್ ಎಷ್ಟು?', 'ಹೋಗಿ ಬನ್ನಿ'],
    explanation: 'ಟಿಕೆಟ್ ಎಷ್ಟು asks the fare on a bus.',
    skillTag: 'listening',
    xp: 3,
    vocabularyIds: ['ticket-eshtu'],
  },
  {
    id: 'survival-speaking-1',
    type: 'speaking',
    prompt: 'Say this phrase:',
    kannada: 'ನಮಸ್ಕಾರ ಸಾರ್',
    transliteration: 'namaskara saar',
    answer: 'namaskara saar',
    options: ['Record', 'Try Again'],
    explanation: 'Stretch the long aa sound in saar.',
    skillTag: 'pronunciation',
    xp: 4,
    vocabularyIds: ['namaskara-saar'],
  },
  {
    id: 'survival-match-1',
    type: 'matchPairs',
    prompt: 'Match the pairs:',
    kannada: 'ನಮಸ್ಕಾರ, ಧನ್ಯವಾದ, ಹೋಗು, ಬಾ',
    answer: 'ನಮಸ್ಕಾರ=Hello;ಧನ್ಯವಾದ=Thank you;ಹೋಗು=Go;ಬಾ=Come',
    options: ['ನಮಸ್ಕಾರ', 'ಧನ್ಯವಾದ', 'ಹೋಗು', 'ಬಾ', 'Hello', 'Thank you', 'Go', 'Come'],
    explanation: 'These are the first useful pairs for survival Kannada.',
    skillTag: 'vocabulary',
    xp: 4,
    vocabularyIds: ['namaskara-saar', 'dhanyavada', 'hogbeku'],
  },
]

const scenarioPhrase = (id: string) => survivalPhrases.find((phrase) => phrase.id === id)!

export const bangaloreScenarios: Scenario[] = [
  {
    id: 'bmtc-bus',
    title: 'BMTC Bus',
    icon: 'BUS',
    difficulty: 'Beginner',
    situation: 'You boarded 500D at Majestic and need a ticket to Koramangala.',
    openingLine: {
      kannada: 'ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು?',
      transliteration: 'ellige hogbeku?',
      english: 'Where do you need to go?',
    },
    checklist: ['Greet conductor', 'Say destination', 'Ask the fare', 'Pay and get ticket'],
    usefulPhrases: [scenarioPhrase('ticket-eshtu'), scenarioPhrase('nidhanavagi-heli')],
  },
  {
    id: 'auto-ride',
    title: 'Auto Ride',
    icon: 'AUTO',
    difficulty: 'Beginner',
    situation: 'You are negotiating an auto from Indiranagar to Majestic.',
    openingLine: {
      kannada: 'ಸಾರ್, ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು?',
      transliteration: 'saar, ellige hogbeku?',
      english: 'Sir, where do you need to go?',
    },
    checklist: ['Say destination', 'Ask fare', 'Confirm meter', 'Ask to stop'],
    usefulPhrases: [scenarioPhrase('majestic-ge-hogbeku'), scenarioPhrase('illi-nillisi')],
  },
  {
    id: 'darshini',
    title: 'Darshini',
    icon: 'FOOD',
    difficulty: 'Beginner',
    situation: 'Order breakfast and filter coffee at a busy standing hotel.',
    openingLine: {
      kannada: 'ಏನು ಬೇಕು?',
      transliteration: 'enu beku?',
      english: 'What do you want?',
    },
    checklist: ['Order food', 'Ask price', 'Say thank you'],
    usefulPhrases: [scenarioPhrase('beku'), scenarioPhrase('dhanyavada')],
  },
  {
    id: 'kirana',
    title: 'Kirana',
    icon: 'SHOP',
    difficulty: 'Beginner',
    situation: 'Buy milk and decline a carry bag at the neighborhood store.',
    openingLine: {
      kannada: 'ಹೇಳಿ ಸಾರ್',
      transliteration: 'heli saar',
      english: 'Tell me, sir.',
    },
    checklist: ['Ask for item', 'Ask price', 'Decline bag'],
    usefulPhrases: [scenarioPhrase('eshtu'), scenarioPhrase('beda')],
  },
  {
    id: 'office',
    title: 'Office',
    icon: 'WORK',
    difficulty: 'Intermediate',
    situation: 'Greet coworkers and answer lunch small talk.',
    openingLine: {
      kannada: 'ಊಟ ಆಯ್ತಾ?',
      transliteration: 'oota aayta?',
      english: 'Did you eat?',
    },
    checklist: ['Greet coworker', 'Answer lunch question', 'Ask them back'],
    usefulPhrases: [scenarioPhrase('oota-aayta'), scenarioPhrase('chennagiddene')],
  },
  {
    id: 'pg-owner',
    title: 'PG Owner',
    icon: 'HOME',
    difficulty: 'Intermediate',
    situation: 'Ask your PG owner about water and maintenance.',
    openingLine: {
      kannada: 'ಏನ್ ಸಮಸ್ಯೆ?',
      transliteration: 'en samasye?',
      english: 'What is the problem?',
    },
    checklist: ['Explain issue', 'Ask when it will come', 'Say thanks'],
    usefulPhrases: [scenarioPhrase('barutte'), scenarioPhrase('matte-heli')],
  },
]

export function getLevelOneCurriculum(): Curriculum {
  return {
    level: 1,
    title: 'Survival Kannada',
    description: 'Real Bangalore Kannada for greetings, transport, food, and everyday help.',
    phrases: survivalPhrases,
    exercises: lessonExercises,
  }
}

export function getExerciseCoverage(): ExerciseType[] {
  return ['translate', 'arrange', 'fillBlank', 'listening', 'speaking', 'matchPairs']
}
